
version: "{build}"

clone_folder: c:\gopath\src\github.com\evshiron\shitama

environment:
  GOPATH: c:\gopath
  QINIU_AK:
    secure: wix+RiWcIDAI99yNUN+faPT6DsoldpNUAlQCw1z12TQNDdzU4gd1DvOzBmpMfYSN
  QINIU_SK:
    secure: sNrdLAohg07//wbx2nc3v4UVt0ryx76Xnq6Wq7SnYYGLjroVCxofplcPqt1fXJQD

install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build_script:
  - .\scripts\build_client_dist.bat %APPVEYOR_BUILD_ID% %APPVEYOR_REPO_COMMIT%

deploy:
  provider: GitHub
  release: r$(APPVEYOR_BUILD_ID)
  description: |
    Shitama r$(APPVEYOR_BUILD_ID) for commit $(APPVEYOR_REPO_COMMIT) in branch $(APPVEYOR_REPO_BRANCH)
  draft: true
  prerelease: true
  auth_token:
    secure: xCaen1KT4SjLSk39zHb+F1m3KfMgHhJfRUiLxqt+rC0BkejW+kmv5iN2Oh7Druzf

artifacts:
  - path: .\dist\Shitama.7z
    name: Shitama

on_success:
  - if "%APPVEYOR_REPO_BRANCH%"=="master" (.\scripts\publish_client_master.bat %QINIU_AK% %QINIU_SK% %APPVEYOR_BUILD_ID%)
  - if "%APPVEYOR_REPO_BRANCH%"=="dev" (.\scripts\publish_client_dev.bat %QINIU_AK% %QINIU_SK% %APPVEYOR_BUILD_ID%)
